-- noinspection SqlResolveForFile
-- noinspection SqlNoDataSourceInspectionForFile

-- -----------------------------------------------------
-- HelloWorld-Addon for OpenEstate-ImmoTool
-- schema for HSQLDB
-- Copyright 2012-2019 OpenEstate.org
-- -----------------------------------------------------

CREATE SEQUENCE seq_immotool_helloworld
  AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE;

-- -----------------------------------------------------
-- Table immotool_helloworld
-- -----------------------------------------------------
CREATE CACHED TABLE immotool_helloworld (
  helloworld_id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_immotool_helloworld NOT NULL,
  helloworld_name VARCHAR(100) NOT NULL,
  helloworld_notes LONGVARCHAR DEFAULT NULL NULL,
  access_owner_id BIGINT DEFAULT NULL NULL,
  access_group_id BIGINT DEFAULT NULL NULL,
  access_permissions INT DEFAULT NULL NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (helloworld_id),
  FOREIGN KEY (access_owner_id)
    REFERENCES immotool_users(user_id)
    MATCH FULL
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (access_group_id)
    REFERENCES immotool_groups(group_id)
    MATCH FULL
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- View view_immotool_helloworld
-- -----------------------------------------------------
CREATE VIEW view_immotool_helloworld AS
  SELECT * FROM immotool_helloworld
  WHERE
  (
    ('DBA' IN (SELECT authorization_name FROM information_schema.authorizations WHERE authorization_type = 'ROLE'))
    OR
    (BITAND(access_permissions, 64) = 64)
    OR
    (BITAND(access_permissions, 8) = 8 AND access_group_id IN (SELECT group_id FROM view_immotool_users_groups WHERE user_login=USER()))
    OR
    (BITAND(access_permissions, 1) = 1 AND access_owner_id IN (SELECT user_id FROM view_immotool_users WHERE user_login=USER()))
  ) WITH CASCADED CHECK OPTION;

GRANT SELECT
  ON view_immotool_helloworld
  TO "IMMOTOOL";
